language: node_js
node_js:
  - "6.9.5"
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
    
install:
  - npm install

scripts:
  - node_modules/karma/bin/karma start karma.conf.js --single-run
  - ng build
  - ng test
  - ng e2e
  

