language: node_js
node_js:
  - "6.9.5"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
install:
  - npm install

scripts:
  - ng build
  - ng test
  - ng e2e
  

