language: node_js
node_js:
  - "6.9.5"
  
install:
  - npm install

scripts:
  - ng build
  - ng test
  - ng e2e

os:
  - linux
  
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser

before_script:
  - sh -e /etc/init.d/xvfb start
